name = "aeneas_playground"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["AeneasPlayground"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[lean_lib]]
name = "AeneasPlayground"

[[require]]
name = "aeneas"
path = "../../aeneas/backends/lean"